### ISSUE TITLE
picoLLM Issue: Cannot run on AArch64 Linux.

### ISSUE THREAD

**Issue by jonahnm** [Picovoice/picollm#36]
### Have you checked the docs and existing issues?

- [X] I have read all of the relevant Picovoice picoLLM docs
- [X] I have searched the existing issues for picoLLM

### SDK

Python

### picoLLM package version

1.0.0

### Framework version

3.11

### Platform

Linux (x86_64)

### OS/Browser version

Termux on Android

### Describe the bug

Attempting to run picoLLM on an aarch64 linux system gives an unsupported CPU error.

### Steps To Reproduce

1. Run picoLLM Python demo on aarch64 linux system
2. Observe unsupported CPU error.

### Expected Behavior

A successful run with the demo opening.

**Comment by ErisMik** [comment]
Thanks for reopening with the template :) 

If I understand correctly, you are trying to use the `desktop Python package` in a `terminal` on an `Android device`? Unfortunately I don't think this is a supported use-case, we have a specific [Android SDK](https://github.com/Picovoice/picollm/tree/main/binding/android) for use on mobile devices. 

Because each binding has to be specifically optimized for each platform that we run on, it is difficult to support niche use cases like yours. However, if this is a commercial application with the budget allocated, feel free to contact the [sales team](https://picovoice.ai/pricing/).

**Comment by jonahnm** [comment]
Ah, I see, I wanted to be able to run it as a server (for a local assistant LLM), is it possible to do that with the Android SDK?

**Comment by jonahnm** [comment]
Oh, wait a minute I just realized there is no builtin server in any of them, I'll just write my own server using the Android SDK, thank you for your time anyways though!

**Comment by ErisMik** [comment]
No problem, good luck!
